### ISSUE TITLE
chromium/3323 missing binaries for OS X and Linux

### ISSUE THREAD

**Issue by jcampbell05** [bblanchon/pdfium-binaries#1]
Just so you know :) happy to help build the linux binaries

**Comment by bblanchon** [comment]
Hi
Please apologies for the late answer.
I'm trying to fix the build, but [I'm still getting link errors](https://travis-ci.org/bblanchon/pdfium-binaries/branches).
Regards,
Benoit

**Comment by jcampbell05** [comment]
No worries :) I'll be happy to help in the future once I've got my head around everything.

**Comment by bblanchon** [comment]
Hi @xiasenhai,

I just fixed the build.
Please check the [release page](https://github.com/bblanchon/pdfium-binaries/releases)

Regards,
Benoit
