### ISSUE TITLE
Can Not load libpdfium.dylib from .NET Core App

### ISSUE THREAD

**Issue by rjskr01** [bblanchon/pdfium-binaries#10]
Trying to call native method using .NET Core app from MAC application got crashed 

For example i have called the following code but it will crashed 

	[DllImport("libpdfium.dylib", CharSet = CharSet.Ansi,CallingConvention =CallingConvention.Cdecl)]
        public static extern IntPtr FPDF_LoadCustomDocument([MarshalAs(UnmanagedType.LPStruct)]FPDF_FILEACCESS access, string password);

**Comment by synercoder** [comment]
Old issue, but I ran into the same problem. After some debugging & building pdfium myself I found out that I did not call FPDF_InitLibrary beforehand.

So before calling any FPDF functions call `FPDF_InitLibrary()` and when done, call `FPDF_DestroyLibrary()`


    public const string LIBRARY_NAME = "libpdfium.dylib";

    [DllImport(LIBRARY_NAME)]
    public static extern void FPDF_InitLibrary();

    [DllImport(LIBRARY_NAME)]
    public static extern void FPDF_DestroyLibrary();

@bblanchon I think you can close this issue now then.
