### ISSUE TITLE
How to build single pdfium.dll

### ISSUE THREAD

**Issue by lazdan** [bblanchon/pdfium-binaries#104]
Hi!
When I make pdfium.dll, I get additional dll's, such as zlib.dll, absl.dll, etc.., which are need in order to use pdfium.dll.
How to configure build, that produce only pdfium.dll including those libs ?
Thank's... )

**Comment by mara004** [comment]
I think, apply [shared_library.patch](https://github.com/bblanchon/pdfium-binaries/blob/master/patches/shared_library.patch) and make sure to set `pdf_is_standalone = true` in the GN config.
