### ISSUE TITLE
Unreal Engine Plugin

### ISSUE THREAD

**Issue by ffreality** [bblanchon/pdfium-binaries#110]
I saw that you have a "Related Projects" section on this repository. I created an Unreal Engine plugin based on your binaries. Is there any code of conduct like requirements to share my project on that section ? My repo.

https://github.com/FF-Projects-UE/PDF_Reader

**Comment by mara004** [comment]
I strongly vote against referencing this project as it does not fulfill minimum code/development quality expectations yet. Take a look at recent conversations on the pdfium mailing list for background.

**Comment by ffreality** [comment]
It is your choice to referencing or not but.

1- It is the strongest Unreal Engine PDF plugin, right now.

2- PDFium doesn't have any documentation or answer for most times. 

3- Your only anchor about my "bad code quality" was about your obsession with char allocation size. They accepted "2" only with couple e-mails. I am sure that even most of them would use "2" before my specific question.

4- And also you... You didn't review my whole code, help about real problems like external web font and image inserting and just say "I AM AGAINST IT BECAUSE HE BROKE MY FEELINGS ABOUT ALLOCATION SIZE"

5- Give me "minimum code quality expectation" , test method, documentation or a review. So, I can improve it.

Without it, you just speak gibberish and you can't say Unreal Engine is dispensable development environment.

**Comment by mara004** [comment]
https://groups.google.com/g/pdfium/c/HwqzzGWWXVU/m/Kzzbm6rHAgAJ
https://groups.google.com/g/pdfium/c/tOLQcjjKS_A

**Comment by mara004** [comment]
Uh, what a waste of time.
Theoretically there would be a lot to say on your comments, but there's not much point.

Mostly what you're writing is groundless. The only matter where I see error on my part was the confusion around the exact amount of excessive allocation, that was a blunder out of tiredness and I already apologized twice.
You're also right I forgot to explicitly mention the NUL terminator once, which was because I only thought about the allocation per char in that context, not about the total amount.

Otherwise, you are being highly impolite and are displaying a behaviour that is not tolerable.

**Comment by mara004** [comment]
I'm wondering if it would be time to file a report to GH support...

**Comment by ffreality** [comment]
> I'm wondering if it would be time to file a report to GH support...

https://youtube.com/shorts/nuiaoaH1zmA?feature=share

**Comment by mara004** [comment]
I'm not looking at the video, for fear it might be something violent or else gravely harassing.
But I reported and blocked you now.

**Comment by ffreality** [comment]
It was breaking bad's "GUS - DOT IT" scene. :D I don't think Youtube or a TV show don't allow a "gravely harrasing" scene.

**Comment by mara004** [comment]
OK, if it really was just a TV show scene. But things are getting a bit too risky for me here, and you never know.

**Comment by ffreality** [comment]
I filed a report about you, too. 

Because you gave `misleading` informations based on my old and solved code which didn't have any previously shared information about correct usage. And I say before, team had to discuss about it.

Also, you didn't have any current bad implementations samples which were not necessary for Unreal Engine.
You didn't give me test method or review it. You judged me directly with my old code.

So, "you" are the risky one in here.
