### ISSUE TITLE
PDFIUM FAILED

### ISSUE THREAD

**Issue by lijuj2** [bblanchon/pdfium-binaries#112]
Hai sirs,

Please find the issue with pdfium. Hope to receive your valued advice.

Best regards.

CMake Error at flutter/ephemeral/.plugin_symlinks/printing/windows/DownloadProject.cmake:179 (message):
  Build step for pdfium failed: 1
Call Stack (most recent call first):
  flutter/ephemeral/.plugin_symlinks/printing/windows/CMakeLists.txt:38 (download_project)

Web no response as well......

**Comment by bblanchon** [comment]
Hi @lijuj2,

This issue is a duplicate of #111.
According to @Sathish0225, you simply need to upgrade to Visual Studio 2022.

Best regards,
Benoit

**Comment by lijuj2** [comment]
Yes, tnx @Emerson, update vs.
