### ISSUE TITLE
Unable to statically link PDFium WASM module

### ISSUE THREAD

**Issue by sungaila** [bblanchon/pdfium-binaries#122]
I tried to make use of the PDFium WASM module in my ASP.NET Core Blazor WebAssembly project [following these steps](https://learn.microsoft.com/en-us/aspnet/core/blazor/webassembly-native-dependencies?view=aspnetcore-7.0). However, the static linking during the build fails with the message `pdfium.wasm: not a relocatable wasm file` (reported by wasm-ld, a WebAssembly lld port).

Searching for a solution I found that `emcc` needs the compiler flag `-s SIDE_MODULE=1` or `-s RELOCATABLE=1` to build relocatable pdfium WASM binaries. [But simply adding this in my fork was not enough.](https://github.com/sungaila/pdfium-binaries/blob/41da68b55eebeb2080d4ae3e1e2e4993b119b918/steps/06-build.sh#L13C3-L23C4)

[Now the workflow build fails with the message `relocation X cannot be used against symbol Y; recompile with -fPIC`.](https://github.com/sungaila/pdfium-binaries/actions/runs/6006754481/job/16291775398#step:11:1179)

I have no knowledge in C++/WebAssembly linking and don't know how to proceed. Is this issue related to the standalone WASM builds #103?

**Comment by bblanchon** [comment]
@jerbob92, can you shed some light on this?

**Comment by sungaila** [comment]
@jerbob92 Thank you so much! Using the `libpdfium.a` file worked perfectly.

@bblanchon I opened PR #123 to modify your GitHub workflow and nuspec files such that referencing [bblanchon.PDFium.WebAssembly](https://www.nuget.org/packages/bblanchon.PDFium.WebAssembly) will work automagically for my use case.

**Comment by bblanchon** [comment]
PR #123 merged!
