### ISSUE TITLE
Where is a NuGet package for Win32 C++ projects?

### ISSUE THREAD

**Issue by afaustas** [bblanchon/pdfium-binaries#125]
Hello,

as far as I see, Win32 PDFium NuGet packages are only available for .NET projects. If there is no package for C++, could you tell me why? If I would create such a package would it be welcome here?

Best Regards
Faustas

**Comment by bblanchon** [comment]
Hello Faustas,

The NuGet package contains the native (i.e. non .NET) DLL, so you can dynamically load it from your native C++ executable.
However, the header files and the `.lib` files are missing.
@sungaila, should we add these files to the package?

Best regards,
Benoit

**Comment by sungaila** [comment]
@bblanchon It is possible to create a NuGet package for both .NET and C++. You'll have to include the header and lib files, and create a targets file to make the C++ compiler aware of these.

I'll give it a try and create a pull request later today or this week.
