### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by sabari3** [bblanchon/pdfium-binaries#13]
Hi,

When I used the binaries from the version [chromium/3671](https://github.com/bblanchon/pdfium-binaries/releases/tag/chromium%2F3671), I am getting access violation issue when the FPDF_LoadPage() method is accessed frequently. The images exported from the binaries are appearing as blank images. But when I used the binaries from the version [chromium/3664](https://github.com/bblanchon/pdfium-binaries/releases/tag/chromium%2F3664), I am not facing the access violation exception and the blank image issue. I used windows-x64 assembly. Can you please check this?

Thanks,
Sabari

**Comment by bblanchon** [comment]
Hi Sabari,

It might simply be a bug.
Can you check with the newer releases?

Regards,
Benoit
