### ISSUE TITLE
How can I build pdfium on arm64 platform?(Debian glibc 2.28)

### ISSUE THREAD

**Issue by MyChuan** [bblanchon/pdfium-binaries#135]
step 1, I'm run the sh by command "./build.sh -b chromium/5670 linux arm64".
step 2, the error is "E: 软件包 libc6-i386 没有可安装候选
E: 无法定位软件包 gcc-9-multilib
E: 无法定位软件包 g++-9-aarch64-linux-gnu
E: 无法按照正则表达式 g++-9-aarch64-linux-gnu 找到任何软件包
E: 软件包 gcc-9-aarch64-linux-gnu:i386 没有可安装候选",
then i comment it out.
step 3, the error is "fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree." when it reaches gclient sync -r origin/chromium/5670 --no-history --shallow, but i can get the codes from gclient, then i copy it in this place.
step 4, the error is "gn gen /root/zbc/projects/pdfium-binaries/pdfium-binaries/pdfium/out
Traceback (most recent call last):
  File "/root/zbc/projects/pdfium-binaries/pdfium-binaries/depot_tools/gn.py", line 14, in <module>
    import gclient_paths
  File "/root/zbc/projects/pdfium-binaries/pdfium-binaries/depot_tools/gclient_paths.py", line 24, in <module>
    def FindGclientRoot(from_dir, filename='.gclient'):
  File "/usr/lib/python3.7/functools.py", line 477, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None
"
How can i resolve the problems? Looking forward to your help.

**Comment by bblanchon** [comment]
Hi @MyChuan,

I had the same error today with the Windows build.
I assumed it was because the Python version was too old, so [I updated the runner](https://github.com/bblanchon/pdfium-binaries/commit/109e1cedaacd779b619f34ab020b1c15cf444957).
Guess what? It worked!

Try to upgrade to Python >= 3.9

Best regards,
Benoit

**Comment by MyChuan** [comment]
> Hi @MyChuan,
> 
> I had the same error today with the Windows build. I assumed it was because the Python version was too old, so [I updated the runner](https://github.com/bblanchon/pdfium-binaries/commit/109e1cedaacd779b619f34ab020b1c15cf444957). Guess what? It worked!
> 
> Try to upgrade to Python >= 3.9
> 
> Best regards, Benoit

OK，let me try it, thank you!

**Comment by MyChuan** [comment]
> Hi @MyChuan,
> 
> I had the same error today with the Windows build. I assumed it was because the Python version was too old, so [I updated the runner](https://github.com/bblanchon/pdfium-binaries/commit/109e1cedaacd779b619f34ab020b1c15cf444957). Guess what? It worked!
> 
> Try to upgrade to Python >= 3.9
> 
> Best regards, Benoit

I get another error，“/root/zbc/projects/pdfium-binaries/pdfium-binaries/.gclient_entries missing, .gclient file in parent directory /root/zbc/projects/pdfium-binaries/pdfium-binaries might not be the file you want to use.
Traceback (most recent call last):
  File "/root/zbc/projects/pdfium-binaries/pdfium-binaries/depot_tools/gn.py", line 93, in <module>
    sys.exit(main(sys.argv))
  File "/root/zbc/projects/pdfium-binaries/pdfium-binaries/depot_tools/gn.py", line 88, in main
    return subprocess.call([gn_path] + args[1:])
  File "/usr/local/python39/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/python39/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/python39/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
”.
I can confirm where this file exists, and contents is ""
![image](https://github.com/bblanchon/pdfium-binaries/assets/29647327/b45ce8e3-00bb-4d92-996c-9b116e62ec85)
,what can i do next?

**Comment by bblanchon** [comment]
Hi @MyChuan,

I don't know.
The build works on Ubuntu, and it's all that matters to me.
As I said in #90:

> The goal of the project is to provide PDFium binaries, nothing more.
> The build scripts in this repository are just a side-product of this process.
> Those scripts only need to run on [GitHub-hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners), and I have no intention of making them portable.
>
> To build PDFium on unsupported Linux distributions, please follow the [official instructions](https://pdfium.googlesource.com/pdfium/).

Thank you for your understanding.

Best regards,
Benoit

**Comment by MyChuan** [comment]
> Hi @MyChuan,
> 
> I don't know. The build works on Ubuntu, and it's all that matters to me. As I said in #90:
> 
> > The goal of the project is to provide PDFium binaries, nothing more.
> > The build scripts in this repository are just a side-product of this process.
> > Those scripts only need to run on [GitHub-hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners), and I have no intention of making them portable.
> > To build PDFium on unsupported Linux distributions, please follow the [official instructions](https://pdfium.googlesource.com/pdfium/).
> 
> Thank you for your understanding.
> 
> Best regards, Benoit

I get, thank you all the same！
