### ISSUE TITLE
Not able to View the border of the Link annotation

### ISSUE THREAD

**Issue by KameshRajendran** [bblanchon/pdfium-binaries#136]
I've examined the document in Adobe Reader and noticed that it displays the border color of the hyperlink. However, when we attempt to open it in Chrome, the border does not appear.

 
![image](https://github.com/bblanchon/pdfium-binaries/assets/25635968/75df5aea-4c7b-4052-a14a-8968a57086a6)

I have a hunch that PDFIUM might lack the capability to read border color and border stroke information. Could you please review the attached document and offer guidance on how to access the border properties of hyperlink annotations using PDFIUM?

Sample document :  [Test doc.pdf](https://github.com/bblanchon/pdfium-binaries/files/12882507/Test.doc.pdf)

**Comment by bblanchon** [comment]
Hi @KameshRajendran,

This project only hosts pre-built versions of PDFium.
Please address your question to the PDFium mailing list.

Best regards,
Benoit
