### ISSUE TITLE
Does it work on MinGW-w64?

### ISSUE THREAD

**Issue by oscarfv** [bblanchon/pdfium-binaries#17]
Hello and first of all thank you for providing the binaries.

I see that `build.sh` mentions `MINGW*`. Does this mean that the build is supposed to work on MSYS2+Mingw-w64 ?

**Comment by bblanchon** [comment]
I never tried.
I added `MINGW*` in an attempt to merge `build.bat` and `build.sh` together, but still using Visual Studio.

**Comment by asmwarrior** [comment]
I would also suggest you could supply a mingw-w64 build.

See some related discussion here: [update pdfium-git / git fetch fails · Issue #6284 · msys2/MINGW-packages](https://github.com/msys2/MINGW-packages/issues/6284#issuecomment-735235787)

Thanks.

**Comment by bblanchon** [comment]
The Windows build works fine with MinGW, no need to make a different build.

However there is a problem with `PDFiumConfig.cmake` because it assumes the compiler is MSVC.
Until I find a better solution, you can replace the `if(MSVC)` with `if(WIN32)` and set `PDFium_ARCH` to `x86` or `x64`.
