### ISSUE TITLE
[Question] Can the Pdfium encrypt or decrypt with password a pdf file?

### ISSUE THREAD

**Issue by duongpt582** [bblanchon/pdfium-binaries#175]
I am thinking about  encrypt or decrypt a pdf file with this library on Android. But i can not find any documents or any source can do it. So if this library can  encrypt or decrypt , what should i do next?

**Comment by bblanchon** [comment]
@duongpt582, please address your questions to [the PDFium group](https://groups.google.com/g/pdfium)

**Comment by duongpt582** [comment]
Do you know how to do it? Please help me!
