### ISSUE TITLE
Request - Please add a build with for Windows with pdf_enable_xfa = false

### ISSUE THREAD

**Issue by markpahulje** [bblanchon/pdfium-binaries#18]
Firstly thanks for doing this project.  I have a request to build pdfium without XFA support, as to reduce possible malicious attack vectors.  I see for win x32 builds you already have disabled Javascript (pdf_enabled_v8 = false, great). Can you add the pdf_enable_xfa = false as well. Either in current build or separate build. Thank you.

**Comment by bblanchon** [comment]
I think that make sense to provide two builds: one full-featured with XFA and v8, and a safe build with minimal features.
I'll do that as soon as I can, hopefully for the next build.

**Comment by markpahulje** [comment]
Many thanks.

**Comment by bblanchon** [comment]
I just realized that XFA requires JavaScript, which requires V8.
So XFA was disabled from the beginning.
I updated the args file to make it explicit.

I still want to provide a full build with XFA and v8, but the build time exceeds one hour.
![image](https://user-images.githubusercontent.com/5462433/56944233-e665c480-6b22-11e9-9439-e9194a8da024.png)
I'll try to make the jumbo build work...

**Comment by markpahulje** [comment]
Super!

**Comment by Whiletru3** [comment]
> I still want to provide a full build with XFA and v8, but the build time exceeds one hour.

it would be nice to have an xfa enable version, +1 for that

**Comment by bblanchon** [comment]
Thanks to PR #23 by @TcT2k, we now have a build with V8 and XFA. 🎉
