### ISSUE TITLE
how to build pdfium only for windows

### ISSUE THREAD

**Issue by alexsantelli** [bblanchon/pdfium-binaries#184]
Hi
I've tried to follow the instructions on https://pdfium.googlesource.com/pdfium/ and build my pdfium library for windows, but after I build my own dll, it has a lot of dependency on other dlls. Your pdfium doesn't have any other dependency. I can use yours to render my pdf files. Can you please let me know how you build your library for Windows?

**Comment by alexsantelli** [comment]
Hi, do you have binaries that support windows XP 32 bit?

**Comment by bblanchon** [comment]
Hi @alexsantelli,

The multiple DLLs are probably caused by the option `is_component_build`.

Chromium doesn't support Windows XP (nor Vista) (see #50)

Best regards,
Benoit

**Comment by alexsantelli** [comment]
Thank you!
