### ISSUE TITLE
Are they c or c++ dll's?

### ISSUE THREAD

**Issue by Soner-A** [bblanchon/pdfium-binaries#19]
Helllo,
Are the binaries c or c++ dll's?
I'm asking because I use a compiler(fpc) that can't handle c++ dlls.

**Comment by bblanchon** [comment]
Hi @Soner-A 

pdfium is a C library.

Best Regards,
Benoit

**Comment by GabMarc** [comment]
@Soner-A hi, did you be able to use pdfium source code in FPC?
