### ISSUE TITLE
chromium/3317

### ISSUE THREAD

**Issue by omascia** [bblanchon/pdfium-binaries#2]
Thank you very much for this project hosting pre-built binaries, that helps a lot to experiment with the library before spending time to properly setup all tools to make self builds.
I see something odd with 3317, there are only archives for Windows, but those are nearly empty (no actual binary in it). Just as if they were the result of an automated build / deploy which failed building.
I'm happily and successfully using the builds from October for now.

**Comment by bblanchon** [comment]
Hi @omascia,

I just fixed the build.
Please check the [release page](https://github.com/bblanchon/pdfium-binaries/releases)

Regards,
Benoit

**Comment by omascia** [comment]
Excellent news! Thank you so much!
