### ISSUE TITLE
Building pdfium for UWP

### ISSUE THREAD

**Issue by homeautomationsys** [bblanchon/pdfium-binaries#25]
@bblanchon 
I have created UWP viewer and tried add the pdfium.dll which built for windows x64 into my viewer using LaodPackagedLibrary method. But it returns a null IntPtr. LoadLibrary method also returned a null IntPtr.
Path.Exist(pathOfDLL) returns true.
My guess was dll was not compatible with UWP app. 
I want to know whether I’m right?
Cause if so, I’m going to start building uwp compatible Pdfium dll. 
Just need clarification and advice at the beginning.

**Comment by bblanchon** [comment]
Hi @homeautomationsys,

I never worked with UWP apps myself, so I don't know the answer.
Hopefully, someone else can answer your question.

Best regards,
Benoit

**Comment by homeautomationsys** [comment]
I found the solution to this.
I had to do two fixes. 
(1). First when we add the dll using “Add Existing item” to the project folder, after selecting the dll, choose “Add as Link” button ( not the “Add” ) button. There is a small arrow head in Add button, from there you can choose Add as Link option.
(2). After building the pdfium.dll, even though it doesn’t get show errors (Using dependencies checker, use can find missing modules) while it is still in the built folder, when you move the dll to your project folder, you might get errors. (eg: when I move my dll to the project folder, I got I’m missing zlib.dll and libc++.dll, So along with pdfium.dll I added those two dlls to the project as well. Then for each dll, I change properties as Content and Copy if newer.

After you fix these issues, building UWP viewer is similar to building a project using .Net C# wrapper.

**Comment by bblanchon** [comment]
Hi @homeautomationsys,

Thank you very much for the update.
Would you mind creating a Pull Request to add this information in the README?

Best regards,
Benoit
