### ISSUE TITLE
FPDF_LoadXFA return false on XFA enabled (with V8)

### ISSUE THREAD

**Issue by Whiletru3** [bblanchon/pdfium-binaries#27]
Hello,

I tried to use the xfa enabled build (using a C# wrapper)

I initialised this way https://github.com/bblanchon/pdfium-binaries#how-to-use-javascript-v8-enabled-binaries for ressources.
Then after loading the document i call FPDF_LoadXFA but it return false :(

I use the pdf attached on this pdfium resolved bug ( https://bugs.chromium.org/p/pdfium/issues/detail?id=1081 ), i can't render the form values.

Do i missed something ?

Thanks
Whiletru3

**Comment by bblanchon** [comment]
@TcT2k, do you think you can help with this?

**Comment by TcT2k** [comment]
I don't have any experience with XFA (Just with PDFs containing javascript).

My first guess would have been a missing call to `FPDF_InitEmbeddedLibraries()` as XFA relies on V8, but as that has already been called, I'm not sure.

@Whiletru3 are you sure the folder contains the res files?
Maybe XFA requires additional initilization? (but I doubt that).

**Comment by Whiletru3** [comment]
Yes I call FPDF_InitEmbeddedLibraries() with the res path

Then after loading the FPDF_Document I call FPDF_LoadXFA

With the pdf (in the bug link) it should render  the missing tables

**Comment by bblanchon** [comment]
I accidentally closed this issue in a commit message, but it was stale anyway.
Please reopen if still relevant.
