### ISSUE TITLE
new release almost Missing dll and lib Files

### ISSUE THREAD

**Issue by cxf2015** [bblanchon/pdfium-binaries#3]
is that ok

**Comment by bblanchon** [comment]
Hi @cxf2015,

I just fixed the build.
Please check the [release page](https://github.com/bblanchon/pdfium-binaries/releases)

Regards,
Benoit

**Comment by homeautomationsys** [comment]
Hi @bblanchon , 
I'm doing an MSc related to PDF Annotations. My supervisor asked me to look into pdfium. 
I built the project by following https://pdfium.googlesource.com/pdfium/ this. But it created lot of lib ,dll files. I want to build it as a single .dll file. Could you please help me with this?

I have already followed https://github.com/pvginkel/PdfiumViewer/wiki/Building-PDFium this URL. But I faced lot of errors after I run :"ninja pdfium". Seems like there were lot of mismatches with header files in 'core' folder,etc. 
I'm using windows machine. My target is to use this .dll file to a build UWP app.

I'm really grateful if you can help me with this. If you can give a step by step guide that would be better.
Thanks
Gayashan (mailgayashan@gmail.com)

**Comment by bblanchon** [comment]
Hi Gayashan,

Please don't hijack unrelated issues.
Everything you need to know is in `appveyor.yml` and `build.bat`.

Best Regards,
Benoit
