### ISSUE TITLE
Is GYP_MSVS_VERSION used?

### ISSUE THREAD

**Issue by gpetrou** [bblanchon/pdfium-binaries#30]
Using dumpbin /headers with pdfium.dll indicates a 14.00 linker version which is VS 2015. So, is GYP_MSVS_VERSION=2017 really used? I also tried to set GYP_MSVS_OVERRIDE_PATH locally, but the result is the same. Perhaps something should change in vs_toolchain.py?

**Comment by bblanchon** [comment]
I'm setting GYP_MSVS_VERSION here:

https://github.com/bblanchon/pdfium-binaries/blob/a493a682cfb067910b1eb6d6bb8ca542198f271d/appveyor.yml#L9

Do you think it is somehow ignored?

**Comment by gpetrou** [comment]
I had a closer look. It seems that this variable is not ignored, but because is_clang is enabled, dumpbin will always show 14.00 version for the linker. I tried 2017 and 2019 values. If I set is_clang to false and do the same, dumpbin will show 14.1x and 14.2x as expected.
