### ISSUE TITLE
Build static library

### ISSUE THREAD

**Issue by paulo-coutinho** [bblanchon/pdfium-binaries#35]
Hi,

I have a similar project like yours (https://github.com/paulo-coutinho/pdfium-lib) and in my case it never generate the "libpdfium.a". Do you know why?

I need join all .o files manually and generate "libpdfium.a" manually.

Can you help me?

Thanks.

**Comment by bblanchon** [comment]
Hi @paulo-coutinho,

Everything is in the build script, please check it out:
https://github.com/bblanchon/pdfium-binaries/blob/master/build.sh

Best regards,
Benoit

**Comment by paulo-coutinho** [comment]
Hi,

I have already updated mine. I discovered new options that do it. My repository always get from latest versions and need options be updated.

Everything is working well now.

Thanks.

**Comment by bblanchon** [comment]
@sommoMicc, you won't find the static libraries here, nor anywhere that I know.
If you need a static build of PDFium, follow [the official build instructions](https://pdfium.googlesource.com/pdfium/).
