### ISSUE TITLE
static libraries?

### ISSUE THREAD

**Issue by peter20051** [bblanchon/pdfium-binaries#36]
Is it possible to include also static libraries or some easy guide how to build them?

**Comment by peter20051** [comment]
Hi, how do you build your pdfium.dll so it has only standard dependencies, meaning kernel32, gdi32 and user32?

I always get also
vcruntime....
libcc...
api-ms-runtime


My args.gn looks like this.

use_goma = false
clang_use_chrome_plugins = false
pdf_is_standalone = true
pdf_use_skia = false
pdf_use_skia_paths = false
is_debug = false
is_component_build = true
pdf_is_complete_lib = false
pdf_enable_xfa = false
pdf_enable_v8 = false
target_cpu = "x86"
is_clang = true

**Comment by willie** [comment]
I know this issue is closed, but a PDFium Linux x86_64 library is only ~15 MB. I'd far prefer to use a static library.

**Comment by fredemmott** [comment]
> If I remember correctly, when I built static libraries of PDFium 2 years ago, there were huge, like several hundred megabytes. Also, I'm pretty sure a static library is tied to the exact compiler version,

On windows, microsoft are starting to use [a hybrid approach](https://github.com/microsoft/WindowsAppSDK/blob/c3013e1ac6ea8472bce037fe5d543d040d22cebf/docs/Coding-Guidelines/HybridCRT.md) to avoid this: in short:

- the C and C++ runtime is split into two parts: the UCRT which is ABI-stable and compiler-version indepedendent, and the compiler-specific part (vcruntime and friends)
- `/MT` forces both to static, `/MD` forces both to dynamic
- you can use `/MT`, then force the linker to dynamic-link the UCRT but keep the compiler-specific parts static: this drastically reduces the size of the output
  - `/DEFAULTLIB:ucrt.lib` - explicitly include the .dll UCRT
  - `/NODEFAULTLIB:libucrt.lib` - explicitly exclude the static UCRT
  
While MS recommend using their msbuild props file, using the compiler + linker flags works in any build system that allows you to override them
