### ISSUE TITLE
License info incomplete

### ISSUE THREAD

**Issue by bgermann** [bblanchon/pdfium-binaries#41]
Is the license info complete? There is a third_party directory which holds components with different licenses that might be included during build.

**Comment by mara004** [comment]
I see. Is it really necessary to include these indirect licenses?

**Comment by bgermann** [comment]
If they are included in the build and their licenses require inclusion of the license in binary distribution: Yes.

**Comment by mara004** [comment]
I'm quite sure the majority is included in the build, and they are mostly under BSD licenses.

**Comment by bgermann** [comment]
Also, it seems like the c++ (and c?) stdlibs are linked statically at least on Linux. So their licenses are to be included as well.

**Comment by bblanchon** [comment]
Hi @bgermann,

Thank you for raising this issue.

Looking at the build logs, we can see that only a bunch of libraries are actually included in the binary:

For the [non-v8 build](https://travis-ci.org/github/bblanchon/pdfium-binaries/jobs/769287138):

* agg23
* freetype
* icu
* lcms
* libjpeg_turbo
* libopenjpeg20
* zlib

For the [v8 build](https://travis-ci.org/github/bblanchon/pdfium-binaries/jobs/769287139):

* agg23
* bigint
* freetype
* icu
* lcms
* libjpeg_turbo
* libopenjpeg20
* libtiff
* lpng16
* zlib

Note: Theses are the names of the subfolders in the "third-party" directory, the actual name of the libraries may differ.

Does anyone volunteers for a PR?

Best regards,
Benoit

**Comment by bgermann** [comment]
bigint: original code is public domain, the pdfium version is licensed under pdfium's license. So this is okay as-is.

freetype: license does not need to be included. An acknowledgement somewhere in the documentation is required that the FreeType code is used.

lpng16 and zlib: There are no requirements on binary distribution. So these are okay as-is.

**Comment by bgermann** [comment]
@mara004 created [LicenseRef-PdfiumThirdParty.txt](https://github.com/pypdfium2-team/pypdfium2/blob/main/LICENSES/LicenseRef-PdfiumThirdParty.txt) for pypdfium2 which includes the needed licenses except for LibTIFF License.

As long as the licences are not a build artefact please just include that file and extend it.

**Comment by mara004** [comment]
Thanks, libtiff license was indeed missing. I've added it.

**Comment by bblanchon** [comment]
I'm not sure where to put theses files.

1. I could append them to the existing LICENSE file at the root of the tarball
2. I could create a new folder (let's say `share/doc/pdfium/licences/`) and put all the files in it
3. I could create one file that adheres to the [debian/copyright](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/) format

What do you recommend?

**Comment by bgermann** [comment]
I would go with 1.

**Comment by bblanchon** [comment]
Here is an extract from the FreeType license:

> Redistribution of  source code  must retain this  license file (`FTL.TXT') unaltered

I guess that excludes options 1. and 2.

Now, if we go with a folder, does `share/doc/pdfium/licences/` work? or is there a more idiomatic choice?

**Comment by bgermann** [comment]
Ah, you are right; the FTL.TXT only has to be provided in SOURCE distributions.

**Comment by bgermann** [comment]
So no need for it as long as you do not distribute the source.

**Comment by bblanchon** [comment]
I aggregated all the licenses in one file, as you wanted.
I followed [@mara004's pattern](https://github.com/pypdfium2-team/pypdfium2/blob/main/LICENSES/LicenseRef-PdfiumThirdParty.txt) and tried to make the files match as much as possible.

You'll get the result in next Monday's build, but here is a preview: 
https://github.com/bblanchon/pdfium-binaries/files/8898439/LICENSE.txt
