### ISSUE TITLE
'pdfium\out-windows-x64-vs\pdfium.dll.lib' & .dll files are not generated

### ISSUE THREAD

**Issue by sparxy3d** [bblanchon/pdfium-binaries#42]
I am trying to build the Pdfium library for a UWP application and when I run the build script, it does not give any build errors but the pdfium.dll.lib & pdfium.dll files are not generated. I have made couple of minor changes to the build script, apart from that there are no other changes.

`set GYP_MSVS_VERSION=2019
set CONFIGURATION=Release
set PLATFORM=x64
set PDFium_BRANCH=master
set PDFium_V8=disabled`

`: Clone
git.exe revert
call gclient config --unmanaged %PDFium_URL% || exit /b
call gclient sync --force --reset || exit /b`

`: Checkout branch (or ignore if it doesn't exist)
echo on
cd %PDFium_SOURCE_DIR%
git.exe checkout %PDFium_BRANCH% && call gclient sync --force --reset`

I am not familiar with Pdfium library and could you please give some guidance with the issue I am facing?
![Untitled](https://user-images.githubusercontent.com/8300823/119447175-21ac3f00-bd4d-11eb-97b5-90727892fd4c.png)
This is the output I am getting from the PS.

**Comment by sparxy3d** [comment]
The issue here was that the patches were not applying while building. So I had to manually apply the patches. After that the build was successful.

**Comment by xtuzy** [comment]
Hi, your dll can do well in uwp and pass windows-app-certification-kit?  I found all dll in github can't pass windows-app-certification-kit, all show need replace some method, but i don't know how to do.
