### ISSUE TITLE
Unable to properly raster a pdf with type 1 fonts on  Linux

### ISSUE THREAD

**Issue by DavBfr** [bblanchon/pdfium-binaries#43]
When rastering [this PDF](http://mathlab.cit.cornell.edu/support/latex/sample/sample.pdf) on Linux using this library, all the text is missing. However, some other features like lines remain visible.
The same file works using the same code on Windows.

![113484099-e2791480-94a6-11eb-8e04-6e4869efc2bf](https://user-images.githubusercontent.com/1387855/123426490-dc706c80-d599-11eb-89f0-9b77c3a63036.png)

This has been reported here: https://github.com/DavBfr/dart_pdf/issues/623
It can be reproduced with all the builds I tested.

The Linux code is here:
https://github.com/DavBfr/dart_pdf/blob/1ca69a1/printing/linux/print_job.cc#L248

The Windows code is here:
https://github.com/DavBfr/dart_pdf/blob/1ca69a1/printing/windows/print_job.cpp#L287

This file contains only embedded Type 1 fonts :

name          | type   | encoding | emb | sub | uni | object ID
------------- | ------ | -------- | --- | --- | --- | ---------
XBSSCH+CMBX12 | Type 1 | Builtin  | yes | yes | no  | 5 0
XYOEFV+CMR10  | Type 1 | Builtin  | yes | yes | no  | 6 0
TPEAAA+CMSY10 | Type 1 | Builtin  | yes | yes | no  | 7 0
JRRGTN+CMTT10 | Type 1 | Builtin  | yes | yes | no  | 8 0
BNTPVG+CMBX10 | Type 1 | Builtin  | yes | yes | no  | 9 0
LLQPUA+CMMI10 | Type 1 | Builtin  | yes | yes | no  | 15 0
JXFAAA+CMMI7  | Type 1 | Builtin  | yes | yes | no  | 16 0
XNAAAA+CMR5   | Type 1 | Builtin  | yes | yes | no  | 17 0
LHCAAA+CMR7   | Type 1 | Builtin  | yes | yes | no  | 18 0
HPAAAA+CMEX10 | Type 1 | Builtin  | yes | yes | no  | 19 0
QSDFAA+CMTI10 | Type 1 | Builtin  | yes | yes | no  | 20 0
XIODEA+CMTI12 | Type 1 | Builtin  | yes | yes | no  | 29 0
LCEAAA+CMBX5  | Type 1 | Builtin  | yes | yes | no  | 34 0
TXDAAA+CMBX9  | Type 1 | Builtin  | yes | yes | no  | 35 0

A file with embedded TTF fonts works:

name              | type         | encoding   | emb | sub | uni | object ID
----------------- | ------------ | ---------- | --- | --- | --- | ---------
Nunito-ExtraLight | CID TrueType | Identity-H | yes | no  | yes | 6 0

**Comment by bblanchon** [comment]
Hi @DavBfr,

I'm just building the binaries; I cannot help you with this issue.
I think you should address this question to the PDFium team.

Best regards,
Benoit

**Comment by mara004** [comment]
Hello,
I tested the mentioned document with current [pypdfium-reboot](https://github.com/mara004/pypdfium-reboot/tree/master/) and cannot reproduce the issue on 64-bit KDE Neon 5.22.2 (Ubuntu 20.04). The document renders just fine:

![02c0b1a26985581409d3494ded19d357](https://user-images.githubusercontent.com/65915611/123678477-a277c280-d846-11eb-8d71-8bd8b8fc1407.png)

**Comment by DavBfr** [comment]
Can it be the init line I use:

```cpp
FPDF_InitLibraryWithConfig(nullptr);
```

Instead of

```cpp
FPDF_LIBRARY_CONFIG config;
  config.version = 2;
  config.m_pUserFontPaths = NULL;
  config.m_pIsolate = NULL;
  config.m_v8EmbedderSlot = 0;

  FPDF_InitLibraryWithConfig(&config);
```

**Comment by DavBfr** [comment]
I'll do more tests, thanks.
