### ISSUE TITLE
Latest 2 releases lack Linux and macOS binaries

### ISSUE THREAD

**Issue by mara004** [bblanchon/pdfium-binaries#44]
https://github.com/bblanchon/pdfium-binaries/releases/tag/chromium%2F4557
https://github.com/bblanchon/pdfium-binaries/releases/tag/chromium%2F4549

**Comment by bblanchon** [comment]
Indeed, I forgot to migrate to travis-ci.com 🤦‍♂️
I'll try to fix this before the next build.

**Comment by mara004** [comment]
No problem, thank you!

**Comment by bblanchon** [comment]
The builds are back, except for the ones with v8 enabled.
I'll write to Travis support to increase the build time limit.

**Comment by mara004** [comment]
Again missing Linux/macOS today

**Comment by bblanchon** [comment]
I triggered a build manually today: https://github.com/bblanchon/pdfium-binaries/releases/tag/chromium%2F4574

**Comment by mara004** [comment]
thanks
