### ISSUE TITLE
File Size

### ISSUE THREAD

**Issue by gamblor999** [bblanchon/pdfium-binaries#45]
Hi Team,

Thanks for the simplyfying the build process for pdfium,  the compiled x64 windows builds on your main page (without XFA and V8) are around 4mb unzipped,  i have used the build script turned off V8 and XFA but am always getting the size of 12mb , how do i get it down to the 4mb ?  what am i doing wrong?

Cheers
Glen

**Comment by bblanchon** [comment]
Hi Glen,

Did you find the answer?

Best regards,
Benoit

**Comment by gamblor999** [comment]
I’d say me doing something wrong, but just edited the build.bat and
replaced the top 5 variables throughout the file in notepad.  This gave me
a 4.3mb file, originally I just edited the windows.arg file and nothing
else so I’m assuming my 12mb file was because I was building for x86 x64
and arm in the one file perhaps, but as I said above I replaced to x86 and
the file has shrunk.

**Comment by gamblor999** [comment]
Benoit I have been using PdfViewer (github by pvginkel) as a wrapper for pdfium.   This wrapper appears to no longer work as "FPDF_Release" is no longer contained in the pdfium.dll.    Do you know if there is a renamed release method i can update the source code for PdfViewer wrapper library?    Alternatively what do you use as a wrapper for .net projects you work with?

**Comment by gamblor999** [comment]
ok so "FPDF_Release" is only in the 32bit pdfium which would mean the PdfViewer wrapper by (pvginkel) is only for 32bit versions of pdfium.   I have a 64 bit system and both 32 & 64 bit work, what are the major benefits of using the 64bit?
