### ISSUE TITLE
FLAG_interpreted_frames_native_stack || !FLAG_jitless not compatible with each other

### ISSUE THREAD

**Issue by RobertMassart** [bblanchon/pdfium-binaries#49]
built with V8 enabled but when testing with:

#include "fpdf_libs.h"

int main()
{
        // Determine the path to files in the res folder from the archive
        const char* resPath = "D:\\pdfium-binaries\\staging\\res\\";

    // Initialize V8 and other embedded libraries
    FPDF_InitEmbeddedLibraries(resPath);

    // Make use of PDFium
    FPDF_InitLibrary();
    FPDF_DestroyLibrary();
}

v8.cc line #178 throws error:
CHECK(!FLAG_interpreted_frames_native_stack || !FLAG_jitless) 

Do you know how to change build to fix this issue?

**Comment by bblanchon** [comment]
@TcT2k, do you have any idea?

**Comment by mm2** [comment]
Also check the path, C language needs double slash \\ in strings.

**Comment by RobertMassart** [comment]
It has double slash, Just cut an paste removed the \\ in the string it really is:

        // Determine the path to files in the res folder from the archive
        const char* resPath = "D:\\pdfium-binaries\\staging\\res\\";

I loads the resources no issue.   Just something else I'm missing.
