### ISSUE TITLE
[Question] Support for Linux with musl rather than glibc

### ISSUE THREAD

**Issue by mara004** [bblanchon/pdfium-binaries#52]
Would it be possible for this project to build binaries for Linux platforms that use the [musl](https://en.wikipedia.org/wiki/Musl) libc implementation rather than [glibc](https://en.wikipedia.org/wiki/Glibc) (e. g. Alpine Linux)? (I got into this topic because I recently noticed that support for musllinux wheels got added to PyPI, cf. [PEP 656](https://www.python.org/dev/peps/pep-0656/).)

**Comment by bblanchon** [comment]
Do you know how we could do that?

**Comment by mara004** [comment]
I'm afraid no - I don't know anything about CI setups. Is Alpine Linux a platform supported by Github Actions?

**Comment by bblanchon** [comment]
No, GitHub Actions only provides Ubuntu hosts.
We could run in a Docker container, but it would be much simpler if we could run this build on the Ubuntu host directly, and I don't see any reason why we couldn't.

However, it seems that Chromium (and thus PDFium) doesn't officially support musl, so the build relies on unofficial patches.
This sounds like a lot of grunt work, I'm not sure I'm willing to go down this road...

**Comment by mara004** [comment]
> However, it seems that Chromium (and thus PDFium) doesn't officially support musl

If musl is not properly supported by PDFium, then I guess trying this will probably be pointless.

**Comment by mara004** [comment]
Now that the userbase of PyPDFium2 seems to be constantly growing, I'd really like to have musl binaries anyway, if it's feasible...

**Comment by mara004** [comment]
Wow, thanks very much! I take it that was quite some hard work.

**Comment by bblanchon** [comment]
It was!
I try to include the ARM builds as well, but run into issues.
Hopefully, I'll be able to add them later.
