### ISSUE TITLE
Arm 64-bit target

### ISSUE THREAD

**Issue by ChristofferGreen** [bblanchon/pdfium-binaries#54]
Hi,

Recently we added a 32-bit arm target to  pdfium-binaries, this target has been working well in Kavita (self-hosted comic/book reader) since then, however, some of our users are running a 64-bit operating system on their raspberry pi and it looks like they are unable to use the 32-bit build.

I know there are issues with Travis credits but I wanted to ask how feasible it would be to add a 64-bit target. If it sounds ok I can see about submitting a pull request.

Thank you

**Comment by bblanchon** [comment]
Hi @ChristofferGreen,

Please check the [latest releases](https://github.com/bblanchon/pdfium-binaries/releases), they already include a Linux build for ARM64.

Best regards,
Benoit

**Comment by ChristofferGreen** [comment]
Oh! That's great! Sorry about not checking first, I just assumed :)
