### ISSUE TITLE
Building broke link for 

### ISSUE THREAD

**Issue by Ros4111** [bblanchon/pdfium-binaries#57]
Hello:
I am trying to upgrade my app with updating the library https://pub.dev/packages/native_pdf_view/versions 4.2 to 5.0 on Windows but it cant finish because is trying to get the file:
https://github.com/bblanchon/pdfium-binaries/releases/download/chromium/4638/pdfium-windows-x64.zip

Could you place again the file so everyone can use?
Regards.

**Comment by bblanchon** [comment]
Hi,

Why don't you download a newer build, like:
https://github.com/bblanchon/pdfium-binaries/releases/latest/download/pdfium-win-x64.tgz

Best regards,
Benoit

**Comment by mara004** [comment]
@Ros4111 As far as I can see, there has not been a release for `4638`. Moreover, please note that the naming changed from `windows` to `win` in case you are downloading the binaries automatically.
