### ISSUE TITLE
cannot launch android application whith libirary 

### ISSUE THREAD

**Issue by MohamedAshraf9** [bblanchon/pdfium-binaries#59]
I have error : dlopen failed: library libabsl.cr.so not found when launch app with android studio

**Comment by mara004** [comment]
Could you please elaborate in which way your issue is connected to pdfium / the binaries published here? How does `libabsl.cr.so` relate to pdfium, and what are you actually trying to achieve?

**Comment by bblanchon** [comment]
The Android build is quite new and I didn't test it.
It's quite possible I forgot to include some pieces.
I'll do some tests and get back to you.
