### ISSUE TITLE
Rendering problem after Ghostscript PDF/A conversion

### ISSUE THREAD

**Issue by hafedh-trimeche** [bblanchon/pdfium-binaries#61]
Hello,

Please note that the file attached is well rendered with **Adobe** & **Foxit** readers but not with **Pdfium** (99.0.4780.0).

Essentially, the borders are not displayed.

[BeforeSign.pdf](https://github.com/bblanchon/pdfium-binaries/files/7759132/BeforeSign.pdf)

Best regards.

**Comment by bblanchon** [comment]
Hi @hafedh-trimeche,

Usually, when parts are missing, it's because forms were not rendered.
See `FPDFDOC_InitFormFillEnvironment()` and `FPDF_FFLDraw()`.

Best regards,
Benoit

**Comment by mara004** [comment]
Is it sufficient to use the `FPDF_ANNOT` flag when rendering, or does one explicitly need to call `FPDFDOC_InitFormFillEnvironment()` in order to display forms correctly?

**Comment by mara004** [comment]
Ah, I got it now. It is necessary to call both `FPDFDOC_InitFormFillEnvironment()` and `FPDF_FFLDraw()`. `FPDF_ANNOT` doesn't make a difference for forms.
