### ISSUE TITLE
Create NuGet packages for PDFium builds 

### ISSUE THREAD

**Issue by sungaila** [bblanchon/pdfium-binaries#65]
Hey there,

are there any plans to distribute these PDFium binaries via NuGet? And if not, could I do that in my own project while referencing this repository?

My [NuGet package PDFtoImage](https://www.nuget.org/packages/PDFtoImage/) redistributes your PDFium native binaries but I'd rather split the binaries into a separate package and create a dependency instead.

**Comment by bblanchon** [comment]
Hi @sungaila,

I didn't have any plan yet, but I could do it.
Should I include PInvoke wrappers or just bundle the binaries?
Do I have to include *all* the binaries in one package? If so, it'll be huge!

I think I should be the one publishing the package because it avoids intermediaries.
Also, I could integrate it with the current CI, so the NuGet package is published immediately.

I left the .NET world a long time ago; I may need some guidance.
Do you think you can write a PR or give me some basic instructions?

Best regards,
Benoit

**Comment by sungaila** [comment]
Hi @bblanchon,

would be awesome if you'd extend the GitHub actions to produce NuGet packages and upload them to nuget.org automatically! I could reference them so my packages won't be as blaoted. 😄

I'd go for a structure SkiaSharp uses:
[SkiaSharp.NativeAssets.Linux](https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux)
[SkiaSharp.NativeAssets.Win32](https://www.nuget.org/packages/SkiaSharp.NativeAssets.Win32)
[SkiaSharp.NativeAssets.macOS](https://www.nuget.org/packages/SkiaSharp.NativeAssets.macOS)
[SkiaSharp.NativeAssets.Android](https://www.nuget.org/packages/SkiaSharp.NativeAssets.Android)
(and many more)

If you peek into those nupkg files (they are simple zip archives) you will find some metadata and build targets for legacy .NET Framework projects. The main content are the native libraries inside the runtimes folder (win-x86, win-arm64, linux-x64, osx-arm64 and so on).

I wouldn't include any .NET code just the plain native PDFium binaries. Wrapping can be offered by other projects like [PDFiumCore](https://github.com/Dtronix/PDFiumCore). Might be hard to auto-generate P/Invoke bindings anyway.

And yes, I'll gladly create a pull request. But first I need to get familiar with those GitHub Actions ...

**Comment by bblanchon** [comment]
Don't bother with the GitHub Actions, I'll handle this.

[I already published on nuget.org](https://www.nuget.org/profiles/bblanchon), but I don't remember how it works.
Can I just follow a basic tutorial?
Should I organize the package in a specific way?
Do you anticipate any issue given the nature of this project?

**Comment by sungaila** [comment]
Well, in that case I guess you have a nuget.org API key for uploading packages already (might need to renew it and put it into GitHub secrets). And you are familiar mit the needed GitHub actions (download nuget.exe, nuget.exe pack and nuget.exe push).

All that's left is the nuspec file that tells nuget.exe how to build the nupkg file. I can give you an example for this.

I'd suggest you name your packages like `bblanchon.PDFium.Win32` or `bblanchon.PDFium.Binaries.Win32`. You can get the prefix `bblanchon` reserved so no one else can upload a pacakge with your personal prefix (this helps against fraud).

The biggest issue I can think of are legacy .NET Framework projects. These need an additional build targets file in your NuGet package file because they are not aware of the runtimes folder. Shouldn't be a problem though.

Also you have to renew your nuget.org API key once a year so your GitHub actions can upload to nuget.org automatically.

Any other potential issues? I can't think of any others right now.
