### ISSUE TITLE
[Question] Boundaries for compatible macOS versions?

### ISSUE THREAD

**Issue by mara004** [bblanchon/pdfium-binaries#68]
Hi @bblanchon,

I'd like to ask what the macOS compatibility boundaries are for the PDFium binaries?
I would need this information to set the correct wheel tags for pypdfium2 on PyPI. 
As `'mac_deployment_target = "10.11.0"'` is defined in `05-configure.sh`, I am currently assuming macOS 10.11 as minimum supported version for both the arm and x64 binaries. I have also enabled compatibility with macOS 11.x using a second platform tag.
Is this correct?

**Comment by mara004** [comment]
Ah, according to Wikipedia, macOS 11 is the first version to support ARM, so I restricted that tag to 11 only.
And what about macOS 12? Would the PDFium binaries be compatible with that, too?

**Comment by bblanchon** [comment]
Hi @mara004,

I assume that your assumptions are correct, but I don't have definite answers to your questions.
These questions should be addressed to the Chromium team; I'm just building a packaging the library.

Best regards,
Benoit

**Comment by mara004** [comment]
Okay, thanks anyway.

**Comment by bblanchon** [comment]
Maybe @TcT2k would know better, he wrote the first macOS build.

**Comment by TcT2k** [comment]
I don't know any better, but would also think min 10.11 for x86 und 11 for arm should be correct. As far as I know the minimum hasn't changed in pdfium. But I haven't used it for a while. But pdfium isn't very SDK dependent (doesn't use any Cocoa stuff) so as long as it compiles with the specified macOS SDK it should also run.

**Comment by mara004** [comment]
@TcT2k Thanks. Do you know anything regarding compatibility with macOS 12? I have now tagged support for it on the off chance, but don't know whether it works.

**Comment by TcT2k** [comment]
I can't think of anything that wouldn't work with MacOS 12
