### ISSUE TITLE
Linux builds for x86 architecture (aka i686)

### ISSUE THREAD

**Issue by mara004** [bblanchon/pdfium-binaries#69]
Hello @bblanchon,

I was wondering whether it would be possible to build pdfium for Linux x86, like the Windows x86 build? I noticed some other Python PDF libraries provide packages for this architecture, so it would be nice if pypdfium2 could do so, too...

Thanks!

**Comment by bblanchon** [comment]
Hi @mara004,

I'll try next week and let you know the result.

Best regards,
Benoit

**Comment by mara004** [comment]
Thanks, take your time. There's no hurry.

**Comment by mara004** [comment]
Nice, thanks so much!
