### ISSUE TITLE
When target_cpu="arm" not working in Android application

### ISSUE THREAD

**Issue by xiasenhai** [bblanchon/pdfium-binaries#7]
i build pdfium-binaries on ubuntu 1804, i modified args/linux.args.gn by appending these two lines:

> **target_cpu="arm"**
> **target_os="linux"**

i set `target_cpu="arm"` , `target_cpu="arm64"` , `target_cpu="x86"`,  `target_cpu="x64"` to build the **armeabi-v7a**, **arm64-v8a**, **x86**, **x86_64** shared library for android, both worked fine on my android app except only when set to `arm` not working.

i tried to set `cFlags = [ "-march=armv7-a", "-mfpu=vfpv3-d16", "-mfloat-abi=hard"]`  in file `pdfium/BUILD.gn`, still not working with same error below:

Build command failed.
Error while executing process /Users/xiasenhai/Library/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /Users/xiasenhai/Downloads/AndroidOfficeApplication/android-pdfium-library/.externalNativeBuild/cmake/debug/armeabi-v7a --target accelerometer}
[1/2] Building CXX object CMakeFiles/accelerometer.dir/sensorgraph.cpp.o
[2/2] Linking CXX shared library /Users/xiasenhai/Downloads/AndroidOfficeApplication/android-pdfium-library/build/intermediates/cmake/debug/obj/armeabi-v7a/libaccelerometer.so
FAILED: : && /Users/xiasenhai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv7-none-linux-androideabi --gcc-toolchain=/Users/xiasenhai/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/xiasenhai/Library/Android/sdk/ndk-bundle/sysroot -fPIC -isystem /Users/xiasenhai/Library/Android/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -mthumb -mfpu=neon -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -fsigned-char -frtti -fexceptions -pthread -std=c++11 -std=c++11 -mthumb -Wall -Werror -O2 -mfpu=neon -mhard-float -D_NDK_MATH_NO_SOFTFP=1 -march=armv7-a -mfloat-abi=hard -O0 -fno-limit-debug-info  -Wl,--fix-cortex-a8 -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot /Users/xiasenhai/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-arm -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--fix-cortex-a8 -Wl,--exclude-libs,libunwind.a -L/Users/xiasenhai/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libaccelerometer.so -o /Users/xiasenhai/Downloads/AndroidOfficeApplication/android-pdfium-library/build/intermediates/cmake/debug/obj/armeabi-v7a/libaccelerometer.so CMakeFiles/accelerometer.dir/sensorgraph.cpp.o  /Users/xiasenhai/Downloads/AndroidOfficeApplication/android-pdfium-library/src/main/cpp/pdfium/lib/armeabi-v7a/libpdfium.so -landroid -lGLESv2 -llog -latomic -lm "/Users/xiasenhai/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++_static.a" "/Users/xiasenhai/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++abi.a" "/Users/xiasenhai/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libunwind.a" "-ldl" && :
/Users/xiasenhai/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: CMakeFiles/accelerometer.dir/sensorgraph.cpp.o uses VFP register arguments, output does not
/Users/xiasenhai/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /Users/xiasenhai/Downloads/AndroidOfficeApplication/android-pdfium-library/src/main/cpp/pdfium/lib/**armeabi-v7a/libpdfium.so uses VFP register arguments, output does not**
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

i also tried these settings on my android app CMakeLists.txt

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O2 -mfpu=neon -mhard-float -D_NDK_MATH_NO_SOFTFP=1 -march=armv7-a -mfloat-abi=hard")

set( ANDROID_LINKER_FLAGS "" )

set( ANDROID_LINKER_FLAGS "-Wl,--fix-cortex-a8" )
set( CMAKE_SHARED_LINKER_FLAGS "${ANDROID_LINKER_FLAGS} ${CMAKE_SHARED_LINKER_FLAGS}" )
set( CMAKE_MODULE_LINKER_FLAGS "${ANDROID_LINKER_FLAGS} ${CMAKE_MODULE_LINKER_FLAGS}" )

**Comment by xiasenhai** [comment]
OK，i think i have to figure this out by myself 😄

**Comment by GabMarc** [comment]
May you share the arm binaries? thanks in advance
