### ISSUE TITLE
Release workflow broken

### ISSUE THREAD

**Issue by mara004** [bblanchon/pdfium-binaries#75]
Hi,

it looks like today's build failed at the pack stage, with the error `steps/07-pack.sh: line 73: V8: unbound variable`, as you can see in https://github.com/bblanchon/pdfium-binaries/actions/runs/2182508607. I would presume that this issue was introduced with commit 79fc39132f209990e78d39bd531d04fe198302d7.

Thanks!

**Comment by bblanchon** [comment]
Hi @mara004,

I received the build failed notification but I couldn't react immediately.

As you can see in the commit you mentioned, I'm renaming the variables so that the match the names in `args.gn`.

I started a new build with the same version; it should be available soon.

Best regards,
Benoit

**Comment by mara004** [comment]
Thanks, no problem. I only intended to notify you in case you hand't noticed the build failure.
