### ISSUE TITLE
Integration of .NET Bindings

### ISSUE THREAD

**Issue by DJGosnell** [bblanchon/pdfium-binaries#77]
Hello, I'm the maintainer of https://github.com/Dtronix/PDFiumCore and I'd like to discuss a potential opportunity to merge my project into yours.
Right now, my project downloads the latest version of your binaries, reads the header file and generates .NET standard bindings.  It then compiles the bindings files along with the binaries into a single NuGet package and uploads it for people to use in their other projects.  This has been fine since your project has historically not created any NuGet packages, but now that packages are being generated, your NuGet packages only have binaries and no way to use them in the .NET world.  I think that this affords an opportunity to incorporate my bindings generation project into yours and then the pdfium-binaries project will be the source for getting the latest binaries, with the latest .NET bindings.

Is this something that you'd be interested in me issuing a PR to integrate? @bblanchon

**Comment by bblanchon** [comment]
Hi @DJGosnell,

Thank you very much for reaching out to me.
Indeed, including the .NET bindings in the NuGet packages would be much more convenient for our users.

I initially thought that your repository consisted of a bunch of `.cs` files with hardcoded P/Invoke functions, which would have been very easy to integrate with this one.
Now, I realize that it's more complicated than I expected: there is a binding generator and a test suite.
The expertise required to maintain this code is significantly different from the one I need in `pdfium-binaries`, so I think it makes sense to keep our repositories separate.

I think the best approach would be to keep your code in its own repo and include your build artifacts in my NuGet packages.
This approach clearly isolates responsibilities while still offering the best user experience.
We just need to figure out a way to do that from my GitHub workflow.
I could check out your main branch and run `dotnet build`, but I think it would be simpler (and less coupled) if I could download your latest build artifacts, which could be either compiled .NET DLLs, or the generated `.cs` files.

Please let me know what you think.

Best regards
Benoit

**Comment by bblanchon** [comment]
@sungaila, I think you might be interested in following this conversation.

**Comment by sungaila** [comment]
> [...] your NuGet packages only have binaries and no way to use them in the .NET world.
Packaging native binaries into NuGet packages only is a perfectly fine use case. E.g. for [SkiaSharp](https://www.nuget.org/packages/SkiaSharp.NativeAssets.Linux) you do not want to include megabytes of binaries if you target a subset of platforms.

[In my case](https://www.nuget.org/packages/PDFtoImage/2.0.0-preview5) I use @bblanchon's NuGet packages directly with the bare minimum of P/Invoke to render PDF files.

@DJGosnell My suggestion to your project would be to remove the native assets from your NuGet packages and to include dependencies to @bblanchon's NuGet packages instead.

This is a cleaner approach and distinguishes the purpose of pdfium-binaries and PDFiumCore: one project provides the native binaries, the other one provides .NET bindings.

**Comment by sungaila** [comment]
@DJGosnell I peeked into your PDFiumCore project and noticed that there are little to no changes to your project when new PDFium binaries are released. Basically, your generator is run, the new C# source files are compiled and pacakged into new NuGet packages.

Maybe a [source generator](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview) would be a better approach: Rebuild your project into a source generator that scans the found PDFium binaries and creates bindings at compile time. You will have to release a NuGet analyzer packages ONCE with no further changes needed.

The advantage: no need to publish new bindings for each and every PDFium release! I can help you to build this, if that idea interests you.

**Comment by DJGosnell** [comment]
Thank you for the feedback.  I think that referencing the binaries Nuget Package and then generating the bindings in a separate package will be the direction I will go in this case. 

Aside. I was unaware that people consumed Nuget packages outside of the .NET ecosystem for tooling and packaging .NET builds.  Is this a common thing that I'm unaware of?

**Comment by sungaila** [comment]
@DJGosnell You are right about NuGet being used for the .NET ecosystem primarily. But there are very few execptions:
> [NuGet frequently-asked questions](https://docs.microsoft.com/en-us/nuget/resources/nuget-faq#what-programming-languages-are-supported-by-nuget-)
NuGet generally works for .NET languages and is designed to bring .NET libraries into a project. Because it also supports MSBuild and Visual Studio automation in some project types, it also supports other projects and languages to various degrees.
**The most recent version of NuGet supports C#, Visual Basic, F#, WiX, and C++.**
