### ISSUE TITLE
Problems with WASM

### ISSUE THREAD

**Issue by paulocoutinhox** [bblanchon/pdfium-binaries#79]
Hi,

Im getting this error with your library.

```
Error while process PDF: abort(Cannot enlarge memory arrays to size 33468416 bytes (OOM). Either (1) compile with -s INITIAL_MEMORY=X with X higher than the current value 16777216, (2) compile with -s ALLOW_MEMORY_GROWTH=1 which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with -s ABORTING_MALLOC=0 ) at Error at jsStackTrace (http://localhost:8000/pdfium.js?v=5028:1706:19) at stackTrace (http://localhost:8000/pdfium.js?v=5028:1728:16) at abort (http://localhost:8000/pdfium.js?v=5028:1442:44) at abortOnCannotGrowMemory (http://localhost:8000/pdfium.js?v=5028:4528:7) at _emscripten_resize_heap (http://localhost:8000/pdfium.js?v=5028:4533:7) at http://localhost:8000/pdfium.wasm:wasm-function[46]:0x6c8d at http://localhost:8000/pdfium.wasm:wasm-function[49]:0x793a at Object._malloc (http://localhost:8000/pdfium.js?v=5028:1492:22) at Processor.getRender (http://localhost:8000/?debug=1:147:37) at Processor.getPageRender (http://localhost:8000/?debug=1:165:42)
```

Try compile with `-s ALLOW_MEMORY_GROWTH=1`.

There is some params that i used:
https://github.com/paulocoutinhox/pdfium-lib/blob/1cc9c1465f1838e4f1d6dfe9ab1e96ad6d0c2b9a/modules/wasm.py#L567-L589

Thanks.

**Comment by bblanchon** [comment]
Hi @paulocoutinhox,

Thank you very much for reporting this.
Next Monday's build will include this flag.
Please let me know if you need any other flags.

Best regards,
Benoit

**Comment by paulocoutinhox** [comment]
Hi,

I tested now and have the same bug than mine version (latest comment):

https://github.com/paulocoutinhox/pdfium-lib/issues/33

![image](https://user-images.githubusercontent.com/395096/171338267-4b12b08f-70f2-4896-b5b7-0f3145170bb1.png)

**Comment by bblanchon** [comment]
I don't think I can do anything about that. Do I?
