### ISSUE TITLE
Add Windows DLL properties during build

### ISSUE THREAD

**Issue by gpetrou** [bblanchon/pdfium-binaries#8]
Would it be possible to add properties to the generated DLLs?
I am mostly interested in the versions.
Currently, they are empty as per the screenshot below.
![emptyproperties](https://user-images.githubusercontent.com/4172445/44626581-b8d2d680-a916-11e8-972a-e7b98ecd0308.png)

**Comment by gpetrou** [comment]
Yes, something like 3608.0 for the chromium/3608 branch would be enough I think.

**Comment by miltontaylor** [comment]
Yes please - such a basic requirement for asset management. This is really important!  The Chrome ver plus build number would be all that's needed.
