### ISSUE TITLE
tagged version chromium/5117 not buildable

### ISSUE THREAD

**Issue by kistlin** [bblanchon/pdfium-binaries#81]
the version tagged with chromium/5117 does not work because all the steps except the tests are commented out.

it fails with

```
+ ENV_FILE=.env
+ PATH_FILE=.path
+ source .env
./build.sh: line 17: .env: No such file or directory
```

because of `# . steps/00-environment.sh`.

it would be convenient if tagged versions build, except they don't have the meaning one would expect :).

**Comment by bblanchon** [comment]
Hi @kistlin,

Thank you for reporting this issue; I accidentally committed this change.

This project uses tags to create a release on GitHub.
You can still build from a tagged revision, but you need to specify the Chromium branch in the right environment variable.
How is this a problem?

Best regards,
Benoit

**Comment by kistlin** [comment]
Thanks for the quick fix @bblanchon.

That's perfectly fine and how one would expect :D. This was just a tease assuming it slipped in by accident. The problem is that this (5117) tagged version did not build (without intervention) ;).
