### ISSUE TITLE
How to configure compilation options

### ISSUE THREAD

**Issue by rgzntrade** [bblanchon/pdfium-binaries#83]
My self-compiled pdfium needs to depend on third-party dlls, how can I use the third-party libraries of static libs? Only depends on pdfium.dll.lib

**Comment by bblanchon** [comment]
Hi @rgzntrade,

The present project hosts precompiled versions of PDFium, that's all.
For any questions related to PDFium, please contact the PDFium mailing list.

Best regards,
Benoit
