### ISSUE TITLE
Static LIB needed

### ISSUE THREAD

**Issue by gorza47** [bblanchon/pdfium-binaries#84]
Hi,

Is there a possibility to get also a static LIB file or your DLL project files?

The static LIB is MUCH bigger ... it would be probably enough OK to get the MSVC (VC2017 and later) project for the DLL and static LIB.
(and built it locally)

Thanks.

**Comment by bblanchon** [comment]
Hi @gorza47,

Static builds were already requested in #36, please see my comments there.

I don't plan on adding the static builds for the moment: it already takes significant time to maintain the 18 shared libraries, and I don't have the bandwidth to work on static libraries.

Best regards,
Benoit

**Comment by gorza47** [comment]
Can you also share your (MSVC) project files for the DLLs?

This would be useful for people who want to build the static LIB or whatever ... without using "depot_tools" etc.

Thanks!

**Comment by mara004** [comment]
All files of the pdfium-binaries project are available in this repository. PDFium is built with Google's toolchain, not MSVC.
