### ISSUE TITLE
Possible checkout speedup

### ISSUE THREAD

**Issue by mara004** [bblanchon/pdfium-binaries#87]
Hi @bblanchon,

I would like to raise awareness of [this pdfium commit](https://pdfium.googlesource.com/pdfium/+/a2ccb26b273ab4d94db117ce2e85263b9e4628c6), which has made checking out Skia and V8 optional. I figured out that a lot of time and disk space is spent working on these.
The checkout may be configured by passing `--custom-var "key=value"` to the `gclient config` command, e. g. `--custom-var "checkout_configuration=minimal"`.
I think you can also selectively define the variables `checkout_skia`, `checkout_v8`, `checkout_testing_corpus` and `checkout_instrumented_libraries`. Probably you could set all of them to `false`, except `checkout_v8` if `$PDFium_ENABLE_V8` is true. This should significantly speed up the checkout process.

Best regards

**Comment by bblanchon** [comment]
Hi @mara004,

It saves almost 3 minutes on the checkout!
This is awesome.
Thanks!

Best regards,
Benoit

**Comment by mara004** [comment]
Thanks! However, the change in its current form breaks the V8 builds. If you plan to restore them at some point, this would need to be taken into account in the checkout step.

**Comment by bblanchon** [comment]
You're right, I added a condition to add this flag only when v8 is disabled.
