### ISSUE TITLE
Linux builds depend on a specific package manager

### ISSUE THREAD

**Issue by kistlin** [bblanchon/pdfium-binaries#90]
Hello,

since some time ago, Linux packages are installed by calling `apt-get` in `steps/01-install.sh`.
This ties the builds down to a handful of Linux distributions.

For now I just patch the lines and install dependencies separately. Which is fine with me.

Long term could there be a command line option added, to not install dependencies?
Or maybe detect the package manager and depending on that install the right packages?

**Comment by bblanchon** [comment]
Hi @kistlin,

The goal of the project is to provide PDFium binaries, nothing more.
The build scripts in this repository are just a side-product of this process.
Those scripts only need to run on [GitHub-hosted runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners), and I have no intention of making them portable.

To build PDFium on unsupported Linux distributions, please follow the [official instructions](https://pdfium.googlesource.com/pdfium/).

Thank you for your understanding.

Best regards,
Benoit
