### ISSUE TITLE
NuGet Package for Wasm

### ISSUE THREAD

**Issue by manfromarce** [bblanchon/pdfium-binaries#94]
I'm using Pdfium in Uno Platform so I'm really thankful to this project which saves me a lot of time when updating binaries. However, would it be possible to also have the Wasm NuGet package?

**Comment by bblanchon** [comment]
@sungaila, could you open a PR to add a WASM package?

@manfromarce, some issues were reported about the WASM build; see #28.
I'd prefer you confirm that the WASM build works for you before we add the NuGet package.

**Comment by manfromarce** [comment]
Yes, it works for me
