### ISSUE TITLE
Include dependencies in v8 releases

### ISSUE THREAD

**Issue by iangudger** [bblanchon/pdfium-binaries#97]
The v8 releases only include `libpdfium.so`, but are missing the other shared objects which I think are required to make the v8 integration work.

When I compiled it, I got the following shared objects:
`libabsl.so`
`libc++.so`
`libchrome_zlib.so`
`libcppgc.so`
`libicui18n.so`
`libicuuc.so`
`libpartition_alloc.so`
`libpdfium.so`
`libv8.so`
`libv8_libbase.so`
`libv8_libplatform.so`

Some of these like `libc++.so` and maybe `libabsl.so` should be provided by the environment, but the v8 ones seem important.

**Comment by bblanchon** [comment]
Hi @iangudger,

I don't see these shared objects in the out directory.
Besides, no one reported a link error.

Best regards,
Benoit

**Comment by mara004** [comment]
I was under the impression that [this patch](https://github.com/bblanchon/pdfium-binaries/blob/master/patches/shared_library.patch) is used to bundle all dependencies in a single pdfium binary?
