### ISSUE TITLE
iOS V8 builds are broken: no release this week 😞 

### ISSUE THREAD

**Issue by bblanchon** [bblanchon/pdfium-binaries#99]
Today's build failed because of a link error caused by the following change:

https://chromium-review.googlesource.com/c/v8/v8/+/4225996

The V8 team reverted the commit, but the PDFium source still points to a faulty version of V8.

**Comment by bblanchon** [comment]
The PDFium team didn't update its V8 version yet, so [the build is still failing](https://github.com/bblanchon/pdfium-binaries/actions/runs/4219936180).
They usually update the V8 dependency every 10 to 30 days, so we might get a build next week 🤞

**Comment by mara004** [comment]
Would it be possible to just release the builds that worked and skip those that failed?
i. e. including V8 builds on an "if it works" basis?

**Comment by bblanchon** [comment]
I'm afraid it could break some builds:

> Shouldn't the release workflow stop if building for one platform fails?
> The scheduled workflow of pypdfium2 currently assumes that all required binaries are present. If this isn't the case, I fear that the repository would be left in a half-broken state, or that some released packages would be invalid.

Source: https://github.com/bblanchon/pdfium-binaries/issues/88#issue-1326023341

It's the first time that the V8 build prevented the non-V8 build from being released; let's see if it happens again before taking radical measures.

Besides, there is probably no significant change in PDFium. If so, you can still download the [build artifacts](https://github.com/bblanchon/pdfium-binaries/actions/runs/4219936180#artifacts).

**Comment by mara004** [comment]
Oh yeah, I remember ;) [^1]
The situation might be a bit different for v8 vs non-v8, but I agree this isn't relevant if it doesn't happen too often.

[^1]: Though nowadays, pypdfium2 should handle missing binaries and abort on its own, I think.
